### PR TITLE
Allow PHPUnit 5.0 as dev dependency

### PR DESCRIPTION
**Pull request by vinkla**
Updated to PHPUnit 5.0 and moved it to require-dev.

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Thanks! This is great.

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
@denis-sokolov could you push a new alpha since the old one is broken?

**Comment by denis-sokolov** [comment]
@vinkla, done.

**Comment by vinkla** [comment]
Thanks!

**Pull request merged**
