### PR TITLE
Universal blacklist.

### PR DESCRIPTION
**Pull request by finagin**
Universal blacklist a sensitive value within one of the superglobal arrays.

### CODE REVIEW

**Comment by barryvdh** [comment]
Yeah was looking in how it was currently tested, but couldn't find it. Not really sure how to test it standalone, as they are private.

**Comment by staabm** [comment]
Ah correct. We dont bave tests for this method

**Comment by SvenRtbg** [comment]
It should still be documented how to use this feature. I.e. at least change the comment for the `blacklist` method to mention that `*` is a wildcard for `_GET, _POST, _FILES, _COOKIES, _SESSION, _SERVER, _ENV`.

One could argue that adding wildcard entries to all these existing arrays instead of adding a new category `*` array (and merging later) is a more straightforward approach and may lead to less trouble whenever changing the `masked(array $superGlobal, $superGlobalName)` method. The current implementation does rely on the blacklist array to be _numerically_ indexed arrays of strings, so `array_merge()` will append everything in the wildcard list, and then reduce double work by applying `array_unique()`.

**Comment by denis-sokolov** [comment]
I’m with @SvenRtbg, this is a good feature, but the number of questions it raises is not worth the minor benefit it brings. If you want to redesign, please don’t be dissuaded by the closing, we can discuss it further.

**Pull request closed without merging**
