### PR TITLE
error-code should be wrapped in ErrorException->severity

### PR DESCRIPTION
**Pull request by staabm**
WIP for issue https://github.com/filp/whoops/issues/267

### CODE REVIEW

**Comment by staabm** [comment]
@denis-sokolov here we go.

**Comment by denis-sokolov** [comment]
Great job, awesome.
Do you mind squashing the commits together? The test and the change related to the test always belong together in my opinion.

**Comment by staabm** [comment]
@denis-sokolov squashed the commits.

small side note: when you as a maintainer like squashed commits instead of separated you should IMO have scripts which would do that for you while merging.
otherwise correct and important PRs might not get merged just because they are contained of X commits instead of 1. Its like dont merge a PR because of CS nits.
But thats just my personal opinion, nothing you should be worried about.

thank you.

**Comment by denis-sokolov** [comment]
I completely agree with you on a general idea of code style and pull requests.
I also do have tools to squash myself, git itself is plenty enough.

Rather, I thought, it was a matter of semantic meaning, and the author is better informed to make correct decisions. For instance, perhaps you see something that I didn't that made you choose a different decision. It seems I have been mistaken and in this particular case it was, indeed, completely arbitrary and I could have done that myself without any risk.

I have a procedure though, and, of course, were you to tell me that you can't or won't squash, I'd help you or pull what I want in whatever order I want myself.

Thank you for your contributions!

**Comment by staabm** [comment]
@denis-sokolv thank for for your time and the great job you are doing.

Wasnt meant to be harsh.

**Pull request merged**
