### PR TITLE
tuned help labels

### PR DESCRIPTION
**Pull request by kminek**

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Could you show a screenshot, please?

**Comment by kminek** [comment]
http://imgur.com/a/EL6FN

**Comment by denis-sokolov** [comment]
Thank you. This looks great.
Perhaps a slightly less vibrant background-color? `#D9AD00`, for example?

**Comment by kminek** [comment]
updated

**Comment by denis-sokolov** [comment]
Thanks for your contribution!

**Pull request merged**
