### PR TITLE
load prettify asynchronously to speedup rendering

### PR DESCRIPTION
**Pull request by staabm**
Inspired by state of the art frontend performance best practices.

### CODE REVIEW

**Comment by staabm** [comment]
This might sometimes lead to code beeing highlighted a bit later, but will lead to earlier execution of the Zepto related JS code in `whoops.base.js`, so user interaction with the page is possible earlier.

**Comment by denis-sokolov** [comment]
Could you put it into a variable instead of sticking it on Zepto?

```js
var getScript = function(){
};
```

And fix the inconsistent quote characters.

A great addition, by the way!

**Comment by staabm** [comment]
@denis-sokolov good point, adjusted per review.

**Comment by denis-sokolov** [comment]
There are more quote characters in that code!

**Comment by staabm** [comment]
@denis-sokolov oh sorry, missed it.

should I fix the quotes in the newly added code or all over the files?

**Comment by denis-sokolov** [comment]
Only the newly added.
It could be a reasonable idea to clean up the entire codebase, but definitely as a separate PR.
In addition, because that involves touching most files, it’s best to be done when there are no active big side branches to avoid conflicts.
At the moment we have that restyling branch, so I would postpone any such cleanup work.

**Comment by staabm** [comment]
@denis-sokolov alright. fixed the quotes.

**Pull request merged**
