### PR TITLE
Add Exception getCode to formatExceptionAsDataArray

### PR DESCRIPTION
**Pull request by CodeBrauer**
According to #673

### CODE REVIEW

**Comment by CodeBrauer** [comment]
I have also thought about adding it in `formatExceptionPlain', but this could be a breaking change for some users should they parse the plaintext with the current version.

**Comment by denis-sokolov** [comment]
Yeah, JSON by default is more extendable, good call with the plain version. Did you try this code yourself already, does it work for you? It’s okay if you didn’t, but want to know what to expect!

**Comment by denis-sokolov** [comment]
Missed comment from the other thread: https://github.com/filp/whoops/issues/673#issuecomment-712698277

Thanks for your contribution! Will release in a moment.

**Comment by CodeBrauer** [comment]
> Yeah, JSON by default is more extendable, good call with the plain version. Did you try this code yourself already, does it work for you? It’s okay if you didn’t, but want to know what to expect!

Yeah works fine.

```php
require __DIR__ . '/../vendor/autoload.php';
$run     = new Whoops\Run;
$handler = new Whoops\Handler\JsonResponseHandler();
$run->pushHandler($handler);
$run->register();
throw new Exception("Error Processing Request", 1024);
```

returns:

```json
{
  "error": {
    "type": "Exception",
    "message": "Error Processing Request",
    "code": 1024,
    "file": "/Users/gw/dev/pr-tester/whoops/examples/json.php",
    "line": 21
  }
}
```

If no code is given, it is `int:0` [by default](https://www.php.net/manual/en/exception.getcode.php#111430) 

_Comment was in wrong thread_

**Pull request merged**
