### PR TITLE
Adjusted editor link color

### LINKED ISSUE #413: Editor link is very low contrast
Editor link is currently styled as nearly black on a very dark background. It's almost impossible to see.

whoops-editor-link

### PR DESCRIPTION
**Pull request by Rarst**
Fixes #413

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Thank you!

**Comment by helhum** [comment]
Any plans when to release this fix?

**Comment by denis-sokolov** [comment]
2.1.3 is out!

**Comment by helhum** [comment]
> 2.1.3 is out!

Indeed, sorry. I have no clue, why composer installed 2.1.2 for me. Updating worked though.

Thanks for your swift response!

**Comment by denis-sokolov** [comment]
You misunderstood me. I meant "thanks for bringing my attention to this, in response to your comment I have now released a new version, yeay!" :)

**Comment by helhum** [comment]
> I meant "thanks for bringing my attention to this

Ah... Now I understand again, why composer installed 2.1.2 :)

I was tricked (and confused) by the release date (which obviously shows the date of the last commit, not the tag creation date):

github-release

So, thanks for the quick release then \o/

**Pull request merged**
