### PR TITLE
Added dumping of variables under code

### PR DESCRIPTION
**Pull request by damnedest**
This is my implementation of this ticket. Since in some cases in left side could be a lot of stuff I draw only types there.

http://imgur.com/xOkkyfI

Related to #337

### CODE REVIEW

**Comment by staabm** [comment]
No sure what you suggest here. The col at the left shows a type and its value, so its not different from #337?

**Comment by damnedest** [comment]
On left column we show only types, on right column under code we show full information about variables

**Comment by staabm** [comment]
I cant follow.
On the left I can see `string(16) 'Something broke'` - which is a type and its value.
In the main column you can see the string `Something broke` - in a place where it is hard to associate the string to be an argument...

Your example should show how things will look when a object or array is passed: the case with a simple string does not represent the worst case.

**Comment by damnedest** [comment]
Close in case of #387

**Pull request closed without merging**
