### PR TITLE
Fix private properties

### PR DESCRIPTION
**Pull request by wawan93**
Replace all private properties to protected, to allow override handlers and exceptions

### CODE REVIEW

**Comment by staabm** [comment]
Whats your use case? Just changing all the properties isnt a good idea.

**Comment by GrahamCampbell** [comment]
👎  on this.

**Comment by wawan93** [comment]
@staabm I need to extend PlainTextHandler and JsonResponseHandler in my project, but I can't because I can't override private methods and properties.

**Comment by staabm** [comment]
@wawan93 could you describe in more detail what are you trying to achieve?

**Comment by denis-sokolov** [comment]
The variables are private on purpose, we do not support extending classes, see #364 and feel free to provide new information if you have any.

**Pull request closed without merging**
