### PR TITLE
Specific-fix for some protocols that quit the page...

### PR DESCRIPTION
**Pull request by Geolim4**
...Such as IntelliJ Platform REST API.

Indeed, as it returns a valid http response, the browser quits the page and then leaves the Whoops page.

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Hm, interesting.
I am worried that on the flip side an Ajax request might not trigger other editors to open.
Could you try a simpler `target=_blank` instead of preventing the default and see if that solves your problem?

**Comment by Geolim4** [comment]
You right, but the problem is as it return a valid http content body, this wont close the tabs but let it open, but i have another idea: What about giving possibility to return an array of attribute with getEditorHref() ?

Current behaviour: Return new link href. (as string)

Proposed behaviour: Return new link href (as string) OR return an array of attributes, e.g. [href => 'blahh', onclick => 'blahh', title => 'blahh'].

Look better for you? :)

**Comment by denis-sokolov** [comment]
No, I dislike giving such power, we'd need to maintain that.
Can you clarify, what is your issue about? If you set your custom links to something custom like `intellij://`, the browser closes the tab after you press on the link?
What about if you set it to `mailto:`? Is it specific to your browser, perhaps? Try another browser.
I'd like to know exactly the circumstances causing this to design the best solution.

**Comment by Geolim4** [comment]
In fact this is not an intellij "protocol" but mostly a local host with a custom port which allow you to send a command to the IDE for opening the file, e.g.
http://localhost:63344/api/file/?file=path_to_the_file&line=line_number&focused=true

The problem is that the API send a valid http body, which cause the browser leaving the page. 
This behavior is totally normal and is the same with all browser (ff, chrome, ie, safari, opera etc.).

**Comment by staabm** [comment]
Why dont you adjust the api?

**Comment by denis-sokolov** [comment]
@staabm, there's not much the server can do to control the browser in that situation, I believe. At best you send 204, but browser behavior is not strictly defined.

@Geolim4, I would accept a patch that would allow callable addEditor/setEditor parameters to return an array: `['url' => '...', 'ajax' => true]`.

**Comment by Geolim4** [comment]
@staabm In fact i have no control to the API, as it handled & managed by phpStorm himself (internally). Also i would like to keep Whoops vanilla as possible.

@denis-sokolov Great decision, i will modify the Pr in hours. Thanks.

**Comment by Geolim4** [comment]
@denis-sokolov
Also i saw in the doc that there's a PhpStormOpener support, but as you can see here:
https://youtrack.jetbrains.com/issue/IDEA-65879#comment=27-913958
JetBrain Team announced the RestFull API (that i am currently trying to implement).
Doc availlable here: http://develar.org/idea-rest-api/

This should deprecate the current (Mac OSX only) phpStorm support, did you confirm it ?

**Comment by denis-sokolov** [comment]
Curent phpStorm support? I [don't think we have it](https://github.com/filp/whoops/blob/f924458af1b06fe6e03fdb0c29322ba011c90ce7/src/Whoops/Handler/PrettyPageHandler.php#L70).

**Comment by Geolim4** [comment]
What About this?
https://github.com/filp/whoops/blob/9f451fbc7b8cad5e71300672c340c28c6bec09ff/docs/Open%20Files%20In%20An%20Editor.md

**Comment by denis-sokolov** [comment]
Ah, well, yes. But it's just a recipe for what you can do in your code. This is unrelated to our code.

**Comment by Geolim4** [comment]
This is why i rewritten this part in @ccd137e :)
All is well else ?

**Comment by denis-sokolov** [comment]
Looks very good! I especially like the proper usage of a data attribute in HTML as opposed to a contrived `onclick` or something.

One final thing - please don't change `getEditorHref` to return an array. Even with options, `getEditorHref` should only return a string, a URL. I suppose you will need a new boolean returning `getEditorAjax` to retrieve the setting in the template.

**Comment by Geolim4** [comment]
So we can do a special method like `getEditorAjax()` ?

**Comment by denis-sokolov** [comment]
Yes.

**Comment by Geolim4** [comment]
Does it look better now? :)

**Comment by denis-sokolov** [comment]
It does. It's not perfect yet, though.
Your implementation of `getEditorAjax` [throws](https://github.com/filp/whoops/pull/282/files#diff-cb7af2a30dcc0c802f01e3dd9c020ef5R374) if the user does not return an array or if the array does not contain `ajax` key. But the majority of users won't, and you should silently handle this.
Consider a helping private function that `getEditorHtml` and `getEditorAjax` share. The function would take whatever the current editor is and normalize it into the widest possible format, with all options defined: `['url' => "", 'ajax' => false]`. Then `getEditorAjax` and `getEditorHtml` are simply `return $this->myHelper(...)['key']` and no matter how many options we add or modify in the future, we only need to edit that helper.

**Comment by Geolim4** [comment]
I will modify that tonight, rhx :)

**Comment by Geolim4** [comment]
I applied an update, it's all ok now?

**Pull request merged**
