### PR TITLE
Fix the bug that call to a member function getFrameFilters() on null

### PR DESCRIPTION
**Pull request by huangdijia**
https://github.com/filp/whoops/blob/3e8aebbca9f0ae6f618962c4ad514077fd365ab3/src/Whoops/Handler/PrettyPageHandler.php#L307

### CODE REVIEW

**Comment by limingxinleo** [comment]
+1

**Comment by AmraniCh** [comment]
You're right, If we need to call a Whoops handler we have to set Its Run instance explicitly.

**Comment by AmraniCh** [comment]
@denis-sokolov

**Comment by denis-sokolov** [comment]
Included in 2.15.1.

**Pull request merged**
