### PR TITLE
Fixed phpunit mess up

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by vinkla** [comment]
Already merged in #353

**Comment by denis-sokolov** [comment]
Thanks, @GrahamCampbell. Don't be mad I accidentally put the PHPUnit in the wrong field! :)

**Comment by vinkla** [comment]
@GrahamCampbell is furious.

furious

**Comment by GrahamCampbell** [comment]
Ha, I'm not mad. ;)

**Pull request closed without merging**
