### PR TITLE
Travis improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
No need to slow down tests with multiple coverage.

Inspiration https://github.com/doctrine/doctrine2/pull/1251

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Great, thank you!

**Comment by TomasVotruba** [comment]
Wow, you're so fast so I haven't checked the tests yet :D.

Thanks!

**Comment by GrahamCampbell** [comment]
This was merged before you pushed those commits...

**Comment by TomasVotruba** [comment]
:+1:

**Comment by denis-sokolov** [comment]
I wondered what was wrong with GitHub. You have submitted the PR, I have waited for the tests to pass and then I merged it in. As soon as I did, I got another message saying you pushed two commits, but the commit hashes matched.
Weird. Oh well.

**Comment by GrahamCampbell** [comment]
> Weird

Yeh, it is. :(

**Pull request merged**
