### PR TITLE
added inline-help for PrettyPage Handler

### PR DESCRIPTION
**Pull request by staabm**
added a inline-help overlay which show up when the user hovers the "HELP" button at the top right.
it describes what the user sees within woops and also mentions possbile keyboard shortcuts (to be implemented in #272)

264zlqd

If we agree on this help-overlay and its styling etc. I would goon and implement the keyboard shortcuts.

### CODE REVIEW

**Comment by denis-sokolov** [comment]
I can stand behind the general idea.

**Comment by denis-sokolov** [comment]
Things I'd love to see improved:
* Avoid marketing language: "at a glance", "integration", "immediately see", "click the button". Currently the language is also a bit inconsistent. "see the line throwing", but "shows all information". I'd suggest short, and formal "Code snippet where the error was thrown", "Server state information", "Exception message and its type".
* Note that there may be more information in the big area on the bottom right. There can be optional data if the application throwing it provides. There's also request data in there.
* Perhaps the hints don't need a title, and can consist only of a short message?

Regardless of my suggestions, it's a good idea and good work is done already, good job!

**Comment by staabm** [comment]
Updated per comments. WDYT?

inlinehelp-v2

**Comment by denis-sokolov** [comment]
I think this looks good!

**Comment by staabm** [comment]
Ok, will add the js handlers for ctrl+up/down then

**Comment by staabm** [comment]
finally added the keyboard shortcuts. this fixes https://github.com/filp/whoops/issues/272

**Comment by staabm** [comment]
@denis-sokolov ready to land.

**Comment by denis-sokolov** [comment]
Do we already have Ctrl+arrows navigation working?

**Comment by staabm** [comment]
Jepp, tested it

**Comment by denis-sokolov** [comment]
Oh, I see, as part of this PR. That got me confused. I'll take a look at it, but great job!

**Comment by staabm** [comment]
@denis-sokolov thanks for merging. would you mind tagging another release?

**Comment by denis-sokolov** [comment]
@staabm, done.

**Pull request merged**
